version: "3"
services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    restart: always
    links:
      - "elasticsearch"
    ports:
      - "${FLUENTD_PORT}:24224"
      - "${FLUENTD_PORT}:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    volumes:
      - ${PWD}/esdata:/usr/share/elasticsearch/data
    restart: always
    expose:
      - "9200"
    ports:
      - "${ELASTIC_PORT}:9200"
    mem_limit: 3gb

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.2.2
    links:
      - "elasticsearch"
    restart: always
    environment:
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: $KIBANA_PASSWORD
    ports:
      - "${KIBANA_PORT}:5601"
